openapi: 3.0.0
info:
  title: MEN REST API
  description: MongoDB ExpressJS NodeJS REST API
  version: 1.0.0
servers:
  - url: http://localhost:4000/api/
    description: Localhost development server 
  - url: https://kenjamin-men-restapi.herokuapp.com/api/
    description: Heroku remote server
components:
  securitySchemes:
    ApiKeyAuth:        # arbitrary name for the security scheme
      type: apiKey
      in: header       # can be "header", "query" or "cookie"
      name: auth-token

  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: number
        inStock:
          type: boolean
    
    User:
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        date:
          type: string

    Cart:
      type: object
      properties:
        userId:
          type: string
        productId:
          type: string
        quantity:
          type: number

    Order:
      type: object
      properties:
        userId:
          type: string
        productId:
          type: string
        quantity:
          type: number
        amount:
          type: number

paths:

  /user/register:
    post:
      summary: Register a new User
      description: Register a new User in the database
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"

      responses:
        201:
          description: User created succesfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  _id:
                    type: string

  /user/login:
    post:
      summary: Login a User
      description: Login a User in order to get JWT token (auth-token)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      
      responses:
        200:
          description: User logged in succesfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                  data:
                    type: string


  /products:
    get:
      summary: Retrieves a list of Products
      description: Retrieves a list of products as JSON objects.
      responses:
        200:
          description: A list of product JSON objects in an array.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
    
    post:
      summary: Create a new Product
      description: Create a new Product
      security:
        - ApiKeyAuth: []      
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"

      responses:
        201:
          description: Product created succesfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
  
  /products/{id}:
    get:
      summary: Specific Product
      description: Retrieves a specific Product based on it id.
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string
      responses:
        200:
          description: A Product in the format of a JSON object.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product"
   
    put:
      summary: Updates a specific Product
      description: Updates a specific Product based on it id
      security:
        - ApiKeyAuth: []            
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"

      responses:
        201:
          description: Product updated succesfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"

    delete:
      summary: Deletes a specific Product
      description: Deletes a specific Product based on it id
      security:
        - ApiKeyAuth: []            
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string      

      responses:
        201:
          description: Product deleted successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"

  

  /cart:
    post:
      summary: Create a new cart item
      description: Create a new cart item
      security:
        - ApiKeyAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Cart"
      
      responses:
        201:
          description: Cart item created successfully
          content:
            application/json:
              schema:
              $ref: "#/components/schemas/Cart"

    get:
      summary: Retrieves a list of cart items
      description: Retrieves a list of cart as JSON objects.
      responses:
        200:
          description: A list of cart JSON objects in an array.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Cart"

  /cart/{id}:
    get:
      summary: Specific Cart Item
      description: Retrieves a specific Cart item based on it id.
      security:
        - ApiKeyAuth: []  
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string
      responses:
        200:
          description: A Cart item in the format of a JSON object.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Cart"

    put:
      summary: Updates a specific Cart item
      description: Updated a specific Cart item based on its id
      security:
        - ApiKeyAuth: []
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Cart"

      responses:
        201:
          description: Cart item updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"

    delete:
      summary: Delete a specific cart item
      description: Deletes a specific cart item based on its id
      security:
        - ApiKeyAuth: []  
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string
      
      responses:
        201:
          description: Cart item delete successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cart"


  /order:
    post:
      summary: Create a new order
      description: Create a new order
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
      
      responses:
        201:
          description: Order created successfully
          content:
            application/json:
              schema:
              $ref: "#/components/schemas/Order"

    get:
      summary: Retrieves a list of ALL orders
      description: Retrieves a list of all orders as a JSON objects.
      responses:
        200:
          description: A list of all orders JSON objects in an array.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"

  /order/{id}:
    get:
      summary: Get Specific Order Item
      description: Retrieves a specific Order item based on its id.
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string
      responses:
        200:
          description: An order item in the format of a JSON object.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Order"

    put:
      summary: Updates a specific Order item
      description: Updated a specific Order item based on its id
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"

      responses:
        201:
          description: Order item updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"

    delete:
      summary: Delete a specific order item
      description: Deletes a specific order item based on its id
      parameters:
        - in: path
          name: id
          required: true
          description: MongoDB id
          schema:
            type: string
      
      responses:
        201:
          description: Order item delete successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"






